### ISSUE TITLE
Installation without cocoapods

### ISSUE THREAD

**Issue by AndrewSB** [venmo/venmo-ios-sdk#77]
I'm trying to add the venmo-ios-sdk to my project without using cocoapods. I've added the repo as a submodule and tried dragging in the xcodeproj, the entire folder, doing `pod install` and then dragging in the entire folder, the xcworkspace to no avail.

No matter what I try, I cannot import the venmo-ios-sdk (`"Venmo-iOS-SDK/Venmo.h file not found"`). 

The README is pretty sparse on how to include the venmo sdk without using cocoapods. Can someone direct me on how to add the venmo library to my project without using Cocoapods?

**Comment by TaterSalad** [comment]
Hi Andrew, I had the exact same problem. I really couldn't figure it out, everyone I asked just told me to start using cocoapods. After a while I caved because cocoapods (once you figure out how to install it and all its components) is really easy to use and powerful. So now I'm gunna suggest you do the same haha

**Comment by AndrewSB** [comment]
@TaterSalad Venmo is a pretty established company and I'm sure they want to be friendly to developers using their platform.
Even if the integration guide is similar to Braintree (https://github.com/braintree/braintree_ios/blob/master/Docs/Manual%20Integration.md), I'd still rather just have a xcodeproj over a workspace.

**Comment by AndrewSB** [comment]
Similar to #39, #43, and #76

**Comment by TaterSalad** [comment]
I totally agree

**Comment by AndrewSB** [comment]
dupe of #39
